program: trian.py
batch_size: 256
data_dir: data/
output_dir: ./weights
save_every: 10
dataset: danube
test_percent: 0.1
epochs: 80
epsilon: 0
lr: 0.001
lr_decay: step
lr_decay_epochs: 26,53
model: resnet18
