program: infer.py
batch_size: 256
data_dir: /home/khaled/workspace/projects/ucl/debiasing/data/
dataset: danube
model: resnet18
model_weights: /home/khaled/workspace/projects/ucl/debiasing/weights/checkpoint_170.pth
yolo_weights: /home/khaled/workspace/projects/ucl/debiasing/weights/DavidK0-YOLOv8-small.pt

